### ISSUE TITLE
Create links schema

### ISSUE THREAD

**Issue by Stihotvor** [Stihotvor/ITSAT#1]
Create schema of links in a DRY manner. All links should be reversible and independent. Self-generation is must. It is better to store links in an application urls.py. 
To do:

- [ ] Create links logical schema
- [ ] Create links django schema
- [ ] Check according to DRY
- [ ] Integrate links schema into the application

**Comment by kurianbenoy** [comment]
what do you mean by DRY principle? 
Should I just create corresponding urls.py in corresponding apps

**Comment by Stihotvor** [comment]
Yes, it's necessary to move url's and import them to the main one. Did You try to launch the project? Also I will update Wiki with proposed link scheme in few days, so that we can discuss it, modify and use.
